### ISSUE TITLE
Add callback method to retrieve generated raw SBD 

### ISSUE THREAD

**Issue by RovoMe** [phax/as2-peppol-client#7]
This is a follow up issue on phax/phase4#34 which targets Peppol AS4, but requests the same for Peppol AS2. The callback in the AS2 case could be [invoked right after the SBD generation](https://github.com/phax/as2-peppol-client/blob/master/src/main/java/com/helger/peppol/as2client/AS2ClientBuilder.java#L1690).

**Comment by phax** [comment]
Will be part of the 3.3.2 release
